### ISSUE TITLE
Add Logout Functionality 

### ISSUE THREAD

**Issue by Bhavik-ag** [Samagra-Development/dsep-ui#10]
Problem
- One the user logins there's no way to logout

Solution
- Add a logout button which clears the user data from localstorage

**Comment by mustafaazad03** [comment]
Hi @Bhavik-ag ,
Can I solve this issue ??

**Comment by Bhavik-ag** [comment]
Heyy @mustafaazad03 I have already raised a PR on this. You can check more issue on https://github.com/Samagra-Development/dsep/issues on this repo.
